// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/cbz.dart';
import 'api/covers.dart';
import 'api/crop.dart';
import 'api/docx.dart';
import 'api/library.dart';
import 'api/mobi.dart';
import 'api/pdf.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1820782025;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_reader_app',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<CropMargins> crateApiCropDetectPdfWhitespace(
      {required String path, required int pageIndex});

  Future<String> crateApiCoversExtractCover(
      {required String bookPath, required String savePath});

  Future<String> crateApiPdfExtractPdfPageText(
      {required String path, required int pageIndex});

  Future<List<PdfTextRect>> crateApiPdfExtractPdfPageTextBounds(
      {required String path,
      required int pageIndex,
      required int startIndex,
      required int endIndex});

  Future<String> crateApiPdfExtractPdfPageTextFromPoint(
      {required String path,
      required int pageIndex,
      required double xNorm,
      required double yNorm});

  Future<CbzPageData> crateApiCbzGetCbzPage(
      {required String path, required int index, int? maxWidth});

  Future<int> crateApiCbzGetCbzPageCount({required String path});

  Future<List<String>> crateApiCbzGetCbzPageNames({required String path});

  String crateApiMobiGetMobiAuthor({required String path});

  String crateApiMobiGetMobiContent({required String path});

  String crateApiMobiGetMobiTitle({required String path});

  Future<int> crateApiPdfGetPdfPageCount({required String path});

  Future<String> crateApiHelloWorld();

  Future<String> crateApiDocxReadDocxToHtml({required String path});

  Future<Uint8List> crateApiPdfRenderPdfPage(
      {required String path,
      required int pageIndex,
      required int width,
      required int height});

  Future<List<BookMetadata>> crateApiLibraryScanLibrary(
      {required String rootPath});

  Future<String> crateApiPdfTestPdfModule();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CropMargins> crateApiCropDetectPdfWhitespace(
      {required String path, required int pageIndex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(pageIndex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_crop_margins,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCropDetectPdfWhitespaceConstMeta,
      argValues: [path, pageIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCropDetectPdfWhitespaceConstMeta =>
      const TaskConstMeta(
        debugName: "detect_pdf_whitespace",
        argNames: ["path", "pageIndex"],
      );

  @override
  Future<String> crateApiCoversExtractCover(
      {required String bookPath, required String savePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bookPath, serializer);
        sse_encode_String(savePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoversExtractCoverConstMeta,
      argValues: [bookPath, savePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoversExtractCoverConstMeta => const TaskConstMeta(
        debugName: "extract_cover",
        argNames: ["bookPath", "savePath"],
      );

  @override
  Future<String> crateApiPdfExtractPdfPageText(
      {required String path, required int pageIndex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(pageIndex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfExtractPdfPageTextConstMeta,
      argValues: [path, pageIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfExtractPdfPageTextConstMeta =>
      const TaskConstMeta(
        debugName: "extract_pdf_page_text",
        argNames: ["path", "pageIndex"],
      );

  @override
  Future<List<PdfTextRect>> crateApiPdfExtractPdfPageTextBounds(
      {required String path,
      required int pageIndex,
      required int startIndex,
      required int endIndex}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(pageIndex, serializer);
        sse_encode_u_32(startIndex, serializer);
        sse_encode_u_32(endIndex, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_pdf_text_rect,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfExtractPdfPageTextBoundsConstMeta,
      argValues: [path, pageIndex, startIndex, endIndex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfExtractPdfPageTextBoundsConstMeta =>
      const TaskConstMeta(
        debugName: "extract_pdf_page_text_bounds",
        argNames: ["path", "pageIndex", "startIndex", "endIndex"],
      );

  @override
  Future<String> crateApiPdfExtractPdfPageTextFromPoint(
      {required String path,
      required int pageIndex,
      required double xNorm,
      required double yNorm}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(pageIndex, serializer);
        sse_encode_f_64(xNorm, serializer);
        sse_encode_f_64(yNorm, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfExtractPdfPageTextFromPointConstMeta,
      argValues: [path, pageIndex, xNorm, yNorm],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfExtractPdfPageTextFromPointConstMeta =>
      const TaskConstMeta(
        debugName: "extract_pdf_page_text_from_point",
        argNames: ["path", "pageIndex", "xNorm", "yNorm"],
      );

  @override
  Future<CbzPageData> crateApiCbzGetCbzPage(
      {required String path, required int index, int? maxWidth}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_i_32(index, serializer);
        sse_encode_opt_box_autoadd_i_32(maxWidth, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_cbz_page_data,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCbzGetCbzPageConstMeta,
      argValues: [path, index, maxWidth],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCbzGetCbzPageConstMeta => const TaskConstMeta(
        debugName: "get_cbz_page",
        argNames: ["path", "index", "maxWidth"],
      );

  @override
  Future<int> crateApiCbzGetCbzPageCount({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCbzGetCbzPageCountConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCbzGetCbzPageCountConstMeta => const TaskConstMeta(
        debugName: "get_cbz_page_count",
        argNames: ["path"],
      );

  @override
  Future<List<String>> crateApiCbzGetCbzPageNames({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCbzGetCbzPageNamesConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCbzGetCbzPageNamesConstMeta => const TaskConstMeta(
        debugName: "get_cbz_page_names",
        argNames: ["path"],
      );

  @override
  String crateApiMobiGetMobiAuthor({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMobiGetMobiAuthorConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobiGetMobiAuthorConstMeta => const TaskConstMeta(
        debugName: "get_mobi_author",
        argNames: ["path"],
      );

  @override
  String crateApiMobiGetMobiContent({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMobiGetMobiContentConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobiGetMobiContentConstMeta => const TaskConstMeta(
        debugName: "get_mobi_content",
        argNames: ["path"],
      );

  @override
  String crateApiMobiGetMobiTitle({required String path}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMobiGetMobiTitleConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMobiGetMobiTitleConstMeta => const TaskConstMeta(
        debugName: "get_mobi_title",
        argNames: ["path"],
      );

  @override
  Future<int> crateApiPdfGetPdfPageCount({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfGetPdfPageCountConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfGetPdfPageCountConstMeta => const TaskConstMeta(
        debugName: "get_pdf_page_count",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiHelloWorld() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHelloWorldConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHelloWorldConstMeta => const TaskConstMeta(
        debugName: "hello_world",
        argNames: [],
      );

  @override
  Future<String> crateApiDocxReadDocxToHtml({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDocxReadDocxToHtmlConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDocxReadDocxToHtmlConstMeta => const TaskConstMeta(
        debugName: "read_docx_to_html",
        argNames: ["path"],
      );

  @override
  Future<Uint8List> crateApiPdfRenderPdfPage(
      {required String path,
      required int pageIndex,
      required int width,
      required int height}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(pageIndex, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfRenderPdfPageConstMeta,
      argValues: [path, pageIndex, width, height],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfRenderPdfPageConstMeta => const TaskConstMeta(
        debugName: "render_pdf_page",
        argNames: ["path", "pageIndex", "width", "height"],
      );

  @override
  Future<List<BookMetadata>> crateApiLibraryScanLibrary(
      {required String rootPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(rootPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_book_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibraryScanLibraryConstMeta,
      argValues: [rootPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibraryScanLibraryConstMeta => const TaskConstMeta(
        debugName: "scan_library",
        argNames: ["rootPath"],
      );

  @override
  Future<String> crateApiPdfTestPdfModule() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPdfTestPdfModuleConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfTestPdfModuleConstMeta => const TaskConstMeta(
        debugName: "test_pdf_module",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BookMetadata dco_decode_book_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BookMetadata(
      title: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CbzPageData dco_decode_cbz_page_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CbzPageData(
      width: dco_decode_i_32(arr[0]),
      height: dco_decode_i_32(arr[1]),
      rgbaBytes: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  CropMargins dco_decode_crop_margins(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CropMargins(
      top: dco_decode_f_32(arr[0]),
      bottom: dco_decode_f_32(arr[1]),
      left: dco_decode_f_32(arr[2]),
      right: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BookMetadata> dco_decode_list_book_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_metadata).toList();
  }

  @protected
  List<PdfTextRect> dco_decode_list_pdf_text_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pdf_text_rect).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PdfTextRect dco_decode_pdf_text_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PdfTextRect(
      left: dco_decode_f_32(arr[0]),
      top: dco_decode_f_32(arr[1]),
      right: dco_decode_f_32(arr[2]),
      bottom: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BookMetadata sse_decode_book_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    return BookMetadata(title: var_title, author: var_author, path: var_path);
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  CbzPageData sse_decode_cbz_page_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_i_32(deserializer);
    var var_height = sse_decode_i_32(deserializer);
    var var_rgbaBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return CbzPageData(
        width: var_width, height: var_height, rgbaBytes: var_rgbaBytes);
  }

  @protected
  CropMargins sse_decode_crop_margins(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_top = sse_decode_f_32(deserializer);
    var var_bottom = sse_decode_f_32(deserializer);
    var var_left = sse_decode_f_32(deserializer);
    var var_right = sse_decode_f_32(deserializer);
    return CropMargins(
        top: var_top, bottom: var_bottom, left: var_left, right: var_right);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookMetadata> sse_decode_list_book_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  List<PdfTextRect> sse_decode_list_pdf_text_rect(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PdfTextRect>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pdf_text_rect(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PdfTextRect sse_decode_pdf_text_rect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_left = sse_decode_f_32(deserializer);
    var var_top = sse_decode_f_32(deserializer);
    var var_right = sse_decode_f_32(deserializer);
    var var_bottom = sse_decode_f_32(deserializer);
    return PdfTextRect(
        left: var_left, top: var_top, right: var_right, bottom: var_bottom);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_book_metadata(BookMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_cbz_page_data(CbzPageData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.width, serializer);
    sse_encode_i_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgbaBytes, serializer);
  }

  @protected
  void sse_encode_crop_margins(CropMargins self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.top, serializer);
    sse_encode_f_32(self.bottom, serializer);
    sse_encode_f_32(self.left, serializer);
    sse_encode_f_32(self.right, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_metadata(
      List<BookMetadata> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pdf_text_rect(
      List<PdfTextRect> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pdf_text_rect(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_pdf_text_rect(PdfTextRect self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.left, serializer);
    sse_encode_f_32(self.top, serializer);
    sse_encode_f_32(self.right, serializer);
    sse_encode_f_32(self.bottom, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
