// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get total number of image pages in a CBZ archive
Future<int> getCbzPageCount({required String path}) =>
    RustLib.instance.api.crateApiCbzGetCbzPageCount(path: path);

/// Get list of page names (sorted) for chapter detection etc
Future<List<String>> getCbzPageNames({required String path}) =>
    RustLib.instance.api.crateApiCbzGetCbzPageNames(path: path);

/// Extract and optionally resize a single page
Future<CbzPageData> getCbzPageByName(
        {required String path, required String entryName, int? maxWidth}) =>
    RustLib.instance.api.crateApiCbzGetCbzPageByName(
        path: path, entryName: entryName, maxWidth: maxWidth);

/// Extract and optionally resize a single page by index.
Future<CbzPageData> getCbzPage(
        {required String path, required int index, int? maxWidth}) =>
    RustLib.instance.api
        .crateApiCbzGetCbzPage(path: path, index: index, maxWidth: maxWidth);

/// Struct to hold extracted page data
class CbzPageData {
  final int width;
  final int height;
  final Uint8List rgbaBytes;

  const CbzPageData({
    required this.width,
    required this.height,
    required this.rgbaBytes,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgbaBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CbzPageData &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgbaBytes == other.rgbaBytes;
}
