// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<CbzHandle> openCbz({required String path, dynamic hint}) =>
    RustLib.instance.api.openCbz(path: path, hint: hint);

Future<int> getCbzPageCount({required CbzHandle handle, dynamic hint}) =>
    RustLib.instance.api.getCbzPageCount(handle: handle, hint: hint);

Future<Uint8List> getCbzPageImage(
        {required CbzHandle handle, required int pageIndex, dynamic hint}) =>
    RustLib.instance.api
        .getCbzPageImage(handle: handle, pageIndex: pageIndex, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<CbzHandle>>
@sealed
class CbzHandle extends RustOpaque {
  CbzHandle.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  CbzHandle.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CbzHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CbzHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CbzHandlePtr,
  );
}
