// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_cbz_cover`, `extract_epub_cover`, `extract_pdf_cover`

/// Extract cover from a book file and save it to the specified path.
/// Returns the saved path on success.
Future<String> extractCover(
        {required String bookPath, required String savePath}) =>
    RustLib.instance.api
        .crateApiCoversExtractCover(bookPath: bookPath, savePath: savePath);
