// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<CropMargins> detectPdfWhitespace(
        {required String path, required int pageIndex}) =>
    RustLib.instance.api
        .crateApiCropDetectPdfWhitespace(path: path, pageIndex: pageIndex);

class CropMargins {
  final double top;
  final double bottom;
  final double left;
  final double right;

  const CropMargins({
    required this.top,
    required this.bottom,
    required this.left,
    required this.right,
  });

  @override
  int get hashCode =>
      top.hashCode ^ bottom.hashCode ^ left.hashCode ^ right.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CropMargins &&
          runtimeType == other.runtimeType &&
          top == other.top &&
          bottom == other.bottom &&
          left == other.left &&
          right == other.right;
}
