// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<DocxHandle> openDocx({required String path, dynamic hint}) =>
    RustLib.instance.api.openDocx(path: path, hint: hint);

Future<String> getDocxText({required DocxHandle handle, dynamic hint}) =>
    RustLib.instance.api.getDocxText(handle: handle, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<DocxHandle>>
@sealed
class DocxHandle extends RustOpaque {
  DocxHandle.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  DocxHandle.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_DocxHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_DocxHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_DocxHandlePtr,
  );
}
