// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> readDocxToHtml({required String path}) =>
    RustLib.instance.api.crateApiDocxReadDocxToHtml(path: path);
