// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<EpubHandle> openEpub({required String path, dynamic hint}) =>
    RustLib.instance.api.openEpub(path: path, hint: hint);

Future<(String, String)> getEpubMetadata(
        {required EpubHandle handle, dynamic hint}) =>
    RustLib.instance.api.getEpubMetadata(handle: handle, hint: hint);

Future<List<String>> getEpubChapters(
        {required EpubHandle handle, dynamic hint}) =>
    RustLib.instance.api.getEpubChapters(handle: handle, hint: hint);

Future<String> getEpubChapterContent(
        {required EpubHandle handle,
        required String chapterId,
        dynamic hint}) =>
    RustLib.instance.api.getEpubChapterContent(
        handle: handle, chapterId: chapterId, hint: hint);

Future<Uint8List> getEpubCover({required EpubHandle handle, dynamic hint}) =>
    RustLib.instance.api.getEpubCover(handle: handle, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<EpubHandle>>
@sealed
class EpubHandle extends RustOpaque {
  EpubHandle.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  EpubHandle.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_EpubHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_EpubHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_EpubHandlePtr,
  );
}
