// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<BookMetadata>> scanLibrary({required String rootPath}) =>
    RustLib.instance.api.crateApiLibraryScanLibrary(rootPath: rootPath);

class BookMetadata {
  final String title;
  final String author;
  final String path;

  const BookMetadata({
    required this.title,
    required this.author,
    required this.path,
  });

  @override
  int get hashCode => title.hashCode ^ author.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          path == other.path;
}
