// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Extracts content from a MOBI file as HTML.
Future<String> getMobiContent({required String path}) =>
    RustLib.instance.api.crateApiMobiGetMobiContent(path: path);

/// Returns the title of a MOBI file.
Future<String> getMobiTitle({required String path}) =>
    RustLib.instance.api.crateApiMobiGetMobiTitle(path: path);

/// Returns the author of a MOBI file.
Future<String> getMobiAuthor({required String path}) =>
    RustLib.instance.api.crateApiMobiGetMobiAuthor(path: path);
