// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_pdfium`
// These functions are ignored because they have generic arguments: `with_pdfium`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get the page count of a PDF file
Future<int> getPdfPageCount({required String path}) =>
    RustLib.instance.api.crateApiPdfGetPdfPageCount(path: path);

/// Render a specific page of a PDF to PNG bytes
Future<Uint8List> renderPdfPage(
        {required String path,
        required int pageIndex,
        required int width,
        required int height}) =>
    RustLib.instance.api.crateApiPdfRenderPdfPage(
        path: path, pageIndex: pageIndex, width: width, height: height);

/// Extract the text of a specific page of a PDF file.
///
/// Notes:
/// - Many PDFs (especially scanned documents) have no text layer, in which case this returns an
///   empty string.
/// - The extracted character order can differ from visual reading order for complex layouts.
Future<String> extractPdfPageText(
        {required String path, required int pageIndex}) =>
    RustLib.instance.api
        .crateApiPdfExtractPdfPageText(path: path, pageIndex: pageIndex);

/// Extract page text starting near a normalized point on the rendered page.
///
/// - `x_norm` / `y_norm` are in the range `[0.0, 1.0]` relative to the full page, with origin
///   at the top-left corner (as in Flutter coordinate space).
/// - If no text is found near the given point (within a tolerance), this returns an empty string.
Future<String> extractPdfPageTextFromPoint(
        {required String path,
        required int pageIndex,
        required double xNorm,
        required double yNorm}) =>
    RustLib.instance.api.crateApiPdfExtractPdfPageTextFromPoint(
        path: path, pageIndex: pageIndex, xNorm: xNorm, yNorm: yNorm);

/// Extract normalized character bounding boxes for a text range on the page.
///
/// The returned rectangles are normalized to the page (0.0-1.0) and use
/// a top-left origin, matching Flutter's coordinate space.
Future<List<PdfTextRect>> extractPdfPageTextBounds(
        {required String path,
        required int pageIndex,
        required int startIndex,
        required int endIndex}) =>
    RustLib.instance.api.crateApiPdfExtractPdfPageTextBounds(
        path: path,
        pageIndex: pageIndex,
        startIndex: startIndex,
        endIndex: endIndex);

/// Pre-compute ALL character bounds for a page.
/// Call this once when loading a page, then use the cached data for TTS highlighting.
/// This eliminates per-word FFI calls during TTS playback.
Future<List<PdfTextRect>> extractAllPageCharacterBounds(
        {required String path, required int pageIndex}) =>
    RustLib.instance.api.crateApiPdfExtractAllPageCharacterBounds(
        path: path, pageIndex: pageIndex);

/// Test function to verify PDF module is working
Future<String> testPdfModule() =>
    RustLib.instance.api.crateApiPdfTestPdfModule();

class PdfTextRect {
  final double left;
  final double top;
  final double right;
  final double bottom;

  const PdfTextRect({
    required this.left,
    required this.top,
    required this.right,
    required this.bottom,
  });

  @override
  int get hashCode =>
      left.hashCode ^ top.hashCode ^ right.hashCode ^ bottom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfTextRect &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          top == other.top &&
          right == other.right &&
          bottom == other.bottom;
}
