// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the page count of a PDF file
Future<int> getPdfPageCount({required String path, dynamic hint}) =>
    RustLib.instance.api.getPdfPageCount(path: path, hint: hint);

/// Render a specific page of a PDF to PNG bytes
Future<Uint8List> renderPdfPage(
        {required String path,
        required int pageIndex,
        required int width,
        required int height,
        dynamic hint}) =>
    RustLib.instance.api.renderPdfPage(
        path: path,
        pageIndex: pageIndex,
        width: width,
        height: height,
        hint: hint);

/// Test function to verify PDF module is working
Future<String> testPdfModule({dynamic hint}) =>
    RustLib.instance.api.testPdfModule(hint: hint);
