// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_text_from_html`, `get_whitespace_regex`, `normalize_text`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Pre-compute all word and sentence boundaries for TTS highlighting.
/// This eliminates per-word computation during TTS playback.
Future<TextHighlightData> precomputeTextHighlights({required String text}) =>
    RustLib.instance.api.crateApiTtsTextPrecomputeTextHighlights(text: text);

/// Find the sentence containing a given character offset
Future<SentenceSpan?> findSentenceForOffset(
        {required List<SentenceSpan> sentences, required int offset}) =>
    RustLib.instance.api.crateApiTtsTextFindSentenceForOffset(
        sentences: sentences, offset: offset);

/// Insert TTS highlight tags into HTML at the specified character range.
/// Uses the scraper crate for fast HTML parsing.
Future<String> insertHtmlHighlight(
        {required String html,
        required int highlightStart,
        required int highlightEnd,
        required String tagName}) =>
    RustLib.instance.api.crateApiTtsTextInsertHtmlHighlight(
        html: html,
        highlightStart: highlightStart,
        highlightEnd: highlightEnd,
        tagName: tagName);

/// Test function for TTS text module
Future<String> testTtsTextModule() =>
    RustLib.instance.api.crateApiTtsTextTestTtsTextModule();

/// A sentence span with character offsets
class SentenceSpan {
  final int start;
  final int end;

  const SentenceSpan({
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SentenceSpan &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

/// Pre-computed text highlight data for fast TTS highlighting
class TextHighlightData {
  final List<WordSpan> words;
  final List<SentenceSpan> sentences;
  final String normalizedText;

  const TextHighlightData({
    required this.words,
    required this.sentences,
    required this.normalizedText,
  });

  @override
  int get hashCode =>
      words.hashCode ^ sentences.hashCode ^ normalizedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextHighlightData &&
          runtimeType == other.runtimeType &&
          words == other.words &&
          sentences == other.sentences &&
          normalizedText == other.normalizedText;
}

/// A word span with character offsets
class WordSpan {
  final int start;
  final int end;
  final String text;

  const WordSpan({
    required this.start,
    required this.end,
    required this.text,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordSpan &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          text == other.text;
}
