// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


Future<TextHighlightData> precomputeTextHighlights({required String text}) =>
    RustLib.instance.api.crateApiTtsTextPrecomputeTextHighlights(text: text);


Future<SentenceSpan?> findSentenceForOffset(
        {required List<SentenceSpan> sentences, required int offset}) =>
    RustLib.instance.api.crateApiTtsTextFindSentenceForOffset(
        sentences: sentences, offset: offset);

Future<String> insertHtmlHighlight(
        {required String html,
        required int highlightStart,
        required int highlightEnd,
        required String tagName}) =>
    RustLib.instance.api.crateApiTtsTextInsertHtmlHighlight(
        html: html,
        highlightStart: highlightStart,
        highlightEnd: highlightEnd,
        tagName: tagName);

Future<String> testTtsTextModule() =>
    RustLib.instance.api.crateApiTtsTextTestTtsTextModule();

class SentenceSpan {
  final int start;
  final int end;

  const SentenceSpan({
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SentenceSpan &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}

class TextHighlightData {
  final List<WordSpan> words;
  final List<SentenceSpan> sentences;
  final String normalizedText;

  const TextHighlightData({
    required this.words,
    required this.sentences,
    required this.normalizedText,
  });

  @override
  int get hashCode =>
      words.hashCode ^ sentences.hashCode ^ normalizedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextHighlightData &&
          runtimeType == other.runtimeType &&
          words == other.words &&
          sentences == other.sentences &&
          normalizedText == other.normalizedText;
}

class WordSpan {
  final int start;
  final int end;
  final String text;

  const WordSpan({
    required this.start,
    required this.end,
    required this.text,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordSpan &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          text == other.text;
}
